use customer_behaviour;

Select *
From customer;

/*Business Insight Questions*/
--1) What is the total revenue generated by male vs female customers?
Select gender, SUM(purchase_amount) AS total_revenue
From customer
Group by gender
Order by total_revenue;

--2) Which customers used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount, discount_applied
From customer
Where discount_applied = 'Yes' 
	AND purchase_amount >= 
		(SELECT AVG(purchase_amount)
		From customer
		);

--3) Which are the top 5 products with the highest average review rating?
Select Top(5) item_purchased, Round(AVG(review_rating),2) average_review
FROM customer
Group by item_purchased
Order by average_review desc;

--4) Compare the average Purchased Amounts between Standard and Express Shipping
Select shipping_type, Round(AVG(purchase_amount),2) AS Average_Purchased_Amounts
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
Group by shipping_type

--5) Do subscribed Customers spend more? Compare average spend and total revenue between subscrbed and non-subscribers
Select subscription_status, 
	Round(Count(customer_id),2) AS total_customer, 
	Round(AVG(purchase_amount),2) AS Average_Spend,
	Round(SUM(purchase_amount),2) AS total_revenue
FROM customer
--WHERE subscription_status BETWEEN 'Yes' AND 'No'
Group by subscription_status
Order by Average_Spend, total_revenue;

--6) Which 5 products have the highest percentage of purchases with discount applied
SELECT Top(5) item_purchased,
Round(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 /COUNT(*),2) 
        AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

--7) Segment Customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment

/*
SELECT
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        WHEN previous_purchases > 5 THEN 'Loyal'
    END AS customer_segment,
    COUNT(*) AS segment_count
FROM customer
GROUP BY previous_purchases
ORDER BY segment_count DESC; */

with customer_cte as (
Select customer_id, previous_purchases,

CASE WHEN previous_purchases = 1 THEN 'New Customer'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning Customer'
			ELSE 'Loyal Customer'
			END AS Customer_Segment
FROM customer
)
select Customer_Segment, count(*) as "Number of Customers"
From customer_cte
Group by Customer_Segment;
--Order by customer_id, previous_purchases;

--8) What are the top 3 most purchased products withn each category
--Solution_1
with item_counts_cte as (
    Select category, item_purchased,
    COUNT(customer_id) as total_orders,
    ROW_NUMBER() OVER(PARTITION BY category order by count(customer_id) DESC) AS item_rank
    FROM customer
    group by category, item_purchased
    )

Select item_rank, category, item_purchased, total_orders
From item_counts_cte
Where item_rank <= 3;

/*
--Solution_2 by ChatGBT
SELECT
    category,
    item_purchased,
    purchase_count
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY category, item_purchased
) AS ranked_products
WHERE rn <= 3
ORDER BY category, purchase_count DESC;
*/

--9) Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,  
    Count(customer_id) AS repeat_buyers
From customer
Where previous_purchases > 5
Group by subscription_status;

--10) What is the revenue contribution of each age group?
Select age_group, SUM(purchase_amount) AS total_revenue
From customer
Group by age_group
Order by total_revenue desc;



